# Generated by Django 5.2.5 on 2025-08-09 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('cyberharcelement', 'Cyberharcèlement'), ('deepfake', 'Deepfake'), ('desinformation', 'Désinformation'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('geolocalisation', models.CharField(blank=True, max_length=255, null=True)),
                ('preuve_image', models.ImageField(blank=True, null=True, upload_to='preuves/images/')),
                ('preuve_video', models.FileField(blank=True, null=True, upload_to='preuves/videos/')),
                ('preuve_log', models.FileField(blank=True, null=True, upload_to='preuves/logs/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='en_attente', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
